# fly.toml app configuration file generated for haazir-backend on 2026-09-07T14:57:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haazir-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_ENV = 'prod'
  COOKIE_SAMESITE = 'none'
  COOKIE_SECURE = 'true'
  LOG_LEVEL = 'INFO'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 180

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
