"""Phase 4 acceptance: the Python estimator reproduces the prototype. Plan §12, §6.

*"A golden-file test reproduces the prototype's numbers for a fixed observation set to three
decimal places."*

`tests/golden/engine_golden.json` is generated by running `app/assets/js/engine.js` itself
under Node (`tests/golden/generate_golden.js`), not by writing down what I believe it does.
That distinction is the entire value of the file: a port checked against its author's
understanding of the original tests nothing.

Regenerate after any deliberate model change:

    node tests/golden/generate_golden.js > tests/golden/engine_golden.json

and read the diff. Every line that moves is a change to what the product tells people.

No database. These are pure functions and they should stay that way.
"""

from __future__ import annotations

import datetime as dt
import json
import pathlib

import pytest

from haazir.estimator import fusion, queueing

GOLDEN_PATH = pathlib.Path(__file__).parent / "golden" / "engine_golden.json"

if not GOLDEN_PATH.exists():  # pragma: no cover
    pytest.skip("golden file missing; run generate_golden.js", allow_module_level=True)

GOLDEN = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))

# "To three decimal places", expressed as a tolerance. `round(a, 3) == round(b, 3)` looks
# equivalent and is not: two values a ten-millionth apart disagree under it whenever they
# straddle a midpoint, which is a property of the comparison rather than of the port.
TOL = 5e-4
EPOCH = dt.datetime(2026, 8, 30, tzinfo=dt.UTC)


def at_minute(m: float) -> dt.datetime:
    """The prototype's clock is minutes since Sunday 00:00; production uses timestamps."""
    return EPOCH + dt.timedelta(minutes=m)


# --- the constants themselves ------------------------------------------------


def test_the_source_table_matches():
    """sigma and tau are the model. A silent edit here changes every estimate in the product
    and nothing else would catch it."""
    for name, spec in GOLDEN["sources"].items():
        assert name in fusion.SOURCES, f"{name} missing from the port"
        ours = fusion.SOURCES[name]
        assert ours["sigma"] == pytest.approx(spec["sigma"]), name
        # JSON has no Infinity; the prototype's `tau: Infinity` serialises to null.
        expected_tau = spec["tau"] if spec["tau"] is not None else None
        assert ours["tau"] == (None if expected_tau is None else pytest.approx(expected_tau))


def test_sigma_ref_matches_the_priors_sd():
    assert fusion.SIGMA_REF == pytest.approx(GOLDEN["sources"]["prior"]["sigma"])


# --- the wait curve ----------------------------------------------------------


def test_the_wait_curve_matches_at_every_point():
    """303 points across three capacity bands, including the kink at rho = 0.72 where the
    curve changes from linear to saturating."""
    mismatches = []
    for row in GOLDEN["wait_at"]:
        ours = queueing.wait_at(row["rho"], row["capacity"])
        if abs(ours - row["wait"]) > TOL:
            mismatches.append((row["capacity"], row["rho"], row["wait"], ours))
    assert mismatches == [], f"{len(mismatches)} points differ, first: {mismatches[:3]}"


def test_the_curve_saturates_rather_than_growing_without_bound():
    assert queueing.wait_at(1.0, 60) <= queueing.MAX_WAIT_MIN
    assert queueing.wait_at(0.99, 60) > queueing.wait_at(0.90, 60)


def test_a_small_room_queues_harder_than_a_large_one():
    """Same 90% full, fewer tables turning over."""
    assert queueing.wait_at(0.90, 60) > queueing.wait_at(0.90, 420)


# --- the band ----------------------------------------------------------------


def test_the_band_thresholds_match():
    for row in GOLDEN["state_band"]:
        assert queueing.state_band(row["x"]) == row["band"], row["x"]


# --- fusion ------------------------------------------------------------------


@pytest.mark.parametrize("case", GOLDEN["fusion"], ids=lambda c: c["name"])
def test_fusion_reproduces_the_prototype(case):
    """The acceptance criterion itself."""
    observations = [
        fusion.Observation(
            source=source,
            value=obs["value"],
            sigma=obs["sigma"],
            observed_at=at_minute(obs["at"]),
            # The prototype has no reporter-trust concept; 1.0 is the neutral equivalent.
            reporter_trust=1.0,
        )
        for source, obs in case["input"].items()
    ]
    result = fusion.fuse(observations, now=at_minute(case["clock"]))
    assert result is not None

    assert result.occupancy == pytest.approx(case["occupancy"], abs=TOL)
    assert result.sd == pytest.approx(case["sd"], abs=TOL)
    assert result.confidence == pytest.approx(case["confidence"], abs=TOL)

    band = queueing.wait_band(result.occupancy, result.sd, case["capacity"])
    assert band["p50"] == pytest.approx(case["wait"], abs=TOL)
    assert band["lo"] == pytest.approx(case["wait_lo"], abs=TOL)
    assert band["hi"] == pytest.approx(case["wait_hi"], abs=TOL)
    assert band["p90"] == pytest.approx(case["wait_p90"], abs=TOL)
    assert queueing.state_band(result.occupancy) == case["band"]


@pytest.mark.parametrize("case", GOLDEN["fusion"], ids=lambda c: c["name"])
def test_the_per_source_weights_reproduce_the_prototype(case):
    """These are shown to the user as the reason to believe the number, so they are part of
    the product's claim, not diagnostics."""
    observations = [
        fusion.Observation(source=s, value=o["value"], sigma=o["sigma"],
                           observed_at=at_minute(o["at"]), reporter_trust=1.0)
        for s, o in case["input"].items()
    ]
    result = fusion.fuse(observations, now=at_minute(case["clock"]))

    ours = {p.source: p.weight for p in result.parts}
    theirs = {p["source"]: p["weight"] for p in case["parts"]}
    assert set(ours) == set(theirs)
    for source, weight in theirs.items():
        assert ours[source] == pytest.approx(weight, abs=TOL), source

    # Ordering matters: the panel lists the strongest contributor first.
    assert [p.source for p in result.parts] == [p["source"] for p in case["parts"]]


def test_weights_sum_to_one():
    for case in GOLDEN["fusion"]:
        observations = [
            fusion.Observation(source=s, value=o["value"], sigma=o["sigma"],
                               observed_at=at_minute(o["at"]), reporter_trust=1.0)
            for s, o in case["input"].items()
        ]
        result = fusion.fuse(observations, now=at_minute(case["clock"]))
        assert sum(p.weight for p in result.parts) == pytest.approx(1.0)


# --- the properties the golden numbers encode --------------------------------


def test_a_prior_alone_has_no_confidence():
    """Confidence is measured against the prior's own sd, so knowing nothing new scores
    zero. A baseline that displayed as 40% confident would be the product lying quietly."""
    result = fusion.fuse(
        [fusion.Observation("prior", 0.42, 0.215, at_minute(1200), reporter_trust=1.0)],
        now=at_minute(1200),
    )
    assert result.confidence == 0.0
    assert result.is_live is False


def test_a_staff_tap_loses_weight_as_it_ages():
    fresh, stale = (
        next(c for c in GOLDEN["fusion"] if c["name"] == n)
        for n in ("prior plus fresh staff tap", "staff tap gone stale")
    )
    fresh_w = next(p["weight"] for p in fresh["parts"] if p["source"] == "staff")
    stale_w = next(p["weight"] for p in stale["parts"] if p["source"] == "staff")
    assert fresh_w > stale_w
    assert fresh["confidence"] > stale["confidence"]


def test_poisson_sigma_decides_how_much_a_payment_reading_counts():
    """The bug this fixed: with one fixed sigma the filter over-trusted small venues and the
    estimate jumped thirty points between frames."""
    sharp = next(c for c in GOLDEN["fusion"]
                 if c["name"] == "sharp payment reading at a large venue")
    vague = next(c for c in GOLDEN["fusion"]
                 if c["name"] == "vague payment reading at a small cash-heavy venue")
    sharp_w = next(p["weight"] for p in sharp["parts"] if p["source"] == "payment")
    vague_w = next(p["weight"] for p in vague["parts"] if p["source"] == "payment")
    assert sharp_w > 0.9
    assert vague_w < 0.3  # the prior rightly dominates a five-tick window


def test_latest_per_source_keeps_only_the_newest():
    """Two readings from one tablet ninety seconds apart are not two pieces of evidence."""
    observations = [
        fusion.Observation("staff", 0.5, 0.05, at_minute(1000)),
        fusion.Observation("staff", 0.9, 0.05, at_minute(1100)),
        fusion.Observation("prior", 0.4, 0.215, at_minute(1100)),
    ]
    latest = fusion.latest_per_source(observations)
    assert len(latest) == 2
    assert next(o for o in latest if o.source == "staff").value == 0.9


def test_double_counting_one_source_would_have_moved_the_estimate():
    """Guards the reason `latest_per_source` exists, rather than trusting the comment."""
    now = at_minute(1100)
    once = fusion.fuse(
        [
            fusion.Observation("staff", 0.9, 0.05, at_minute(1100), reporter_trust=1.0),
            fusion.Observation("prior", 0.4, 0.215, at_minute(1100), reporter_trust=1.0),
        ],
        now=now,
    )
    twice = fusion.fuse(
        [
            fusion.Observation("staff", 0.9, 0.05, at_minute(1100), reporter_trust=1.0),
            fusion.Observation("staff", 0.9, 0.05, at_minute(1099), reporter_trust=1.0),
            fusion.Observation("prior", 0.4, 0.215, at_minute(1100), reporter_trust=1.0),
        ],
        now=now,
    )
    assert twice.sd < once.sd  # a fake certainty gain
    assert twice.confidence > once.confidence


def test_reporter_trust_lowers_a_sources_weight():
    now = at_minute(1100)
    trusted = fusion.fuse(
        [fusion.Observation("checkin", 0.9, 0.14, now, reporter_trust=1.0),
         fusion.Observation("prior", 0.4, 0.215, now, reporter_trust=1.0)], now=now
    )
    doubted = fusion.fuse(
        [fusion.Observation("checkin", 0.9, 0.14, now, reporter_trust=0.05),
         fusion.Observation("prior", 0.4, 0.215, now, reporter_trust=1.0)], now=now
    )
    tw = next(p.weight for p in trusted.parts if p.source == "checkin")
    dw = next(p.weight for p in doubted.parts if p.source == "checkin")
    assert dw < tw / 5


def test_no_observations_returns_none_rather_than_a_number():
    assert fusion.fuse([], now=at_minute(0)) is None


def test_an_unknown_source_is_ignored_not_guessed_at():
    result = fusion.fuse(
        [fusion.Observation("astrology", 0.99, 0.01, at_minute(0)),
         fusion.Observation("prior", 0.40, 0.215, at_minute(0))],
        now=at_minute(0),
    )
    assert [p.source for p in result.parts] == ["prior"]
    assert result.occupancy == pytest.approx(0.40)


# --- trend -------------------------------------------------------------------


def test_trend_is_zero_without_enough_history():
    now = at_minute(1000)
    assert fusion.trend_per_hour([], now) == 0.0
    assert fusion.trend_per_hour([(at_minute(995), 0.5), (at_minute(999), 0.7)], now) == 0.0


def test_trend_reads_a_filling_room_as_positive():
    now = at_minute(1000)
    history = [(at_minute(1000 - k), 0.9 - k * 0.01) for k in (20, 15, 10, 5, 0)]
    trend = fusion.trend_per_hour(history, now)
    assert trend > 0
    assert trend == pytest.approx(0.6, abs=1e-6)  # 0.01/min = 0.6/hour


def test_trend_ignores_history_outside_the_window():
    now = at_minute(1000)
    history = [(at_minute(500), 0.1), (at_minute(600), 0.2), (at_minute(700), 0.3)]
    assert fusion.trend_per_hour(history, now) == 0.0


# --- inverting the curve -----------------------------------------------------


def test_a_typed_wait_maps_back_to_an_occupancy():
    """Staff can tap a band and also type "25 minutes". The band is four buckets; the typed
    number is far sharper, and this is what turns it into the filter's units."""
    for target in (10.0, 25.0, 40.0):
        rho = queueing.occupancy_for_wait(target, capacity=120)
        assert queueing.wait_at(rho, 120) == pytest.approx(target, abs=1.0)


def test_wait_drops_below_finds_a_quieter_hour():
    curve = [0.95 if (h % 24) in (19, 20, 21) else 0.30 for h in range(168)]
    found = queueing.wait_drops_below(
        current_occupancy=0.95, prior_curve=curve, hour_of_week_now=20,
        target_min=8.0, capacity=120,
    )
    assert found is not None
    assert found["in_min"] > 0


def test_wait_drops_below_returns_none_when_already_quiet():
    curve = [0.30] * 168
    assert queueing.wait_drops_below(0.30, curve, 20, 8.0, 120) is None
